version: '3.9'

services:
  divergent-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: divergent-client
    working_dir: /app
    ports:
      - "8085:3000"
    restart: always
