export const appPalette = {
  surface: {
    background: "#ffffff",
    foreground: "#030213",
    card: "#ffffff",
    cardForeground: "#030213",
    cardGroup: "rgba(0, 0, 0, 0.05)",
    popover: "#ffffff",
    popoverForeground: "#030213",
    overlay: "rgba(15, 23, 42, 0.35)",
  },
  brand: {
    primary: "#2296f3",
    primaryStrong: "#2563eb",
    primaryRgb: "34 150 243",
    primaryForeground: "#ffffff",
    ai: "#a855f7",
    aiForeground: "#ffffff",
  },
  ui: {
    secondary: "oklch(0.95 0.0058 264.53)",
    secondaryForeground: "#030213",
    muted: "#ececf0",
    mutedForeground: "#717182",
    accent: "#e9ebef",
    accentForeground: "#030213",
    destructive: "#d4183d",
    destructiveForeground: "#ffffff",
    border: "rgba(0, 0, 0, 0.1)",
    input: "transparent",
    inputBackground: "#f3f3f5",
    switchBackground: "#cbced4",
    ring: "oklch(0.708 0 0)",
  },
  charts: {
    chart1: "oklch(0.646 0.222 41.116)",
    chart2: "oklch(0.6 0.118 184.704)",
    chart3: "oklch(0.398 0.07 227.392)",
    chart4: "oklch(0.828 0.189 84.429)",
    chart5: "oklch(0.769 0.188 70.08)",
  },
  sidebar: {
    background: "oklch(0.985 0 0)",
    foreground: "#030213",
    primary: "#030213",
    primaryForeground: "oklch(0.985 0 0)",
    accent: "oklch(0.97 0 0)",
    accentForeground: "oklch(0.205 0 0)",
    border: "oklch(0.922 0 0)",
    ring: "oklch(0.708 0 0)",
  },
  semantic: {
    textStrong: "#0f172a",
    text: "#334155",
    textMuted: "#64748b",
    textSubtle: "#94a3b8",
    textInverse: "#ffffff",
    borderSubtle: "#e2e8f0",
    borderStrong: "#cbd5e1",
    infoSurface: "#dbeafe",
    infoText: "#1d4ed8",
    infoTextStrong: "#1e3a8a",
    infoBorder: "#93c5fd",
    infoSurfaceStrong: "#eff6ff",
    successSurface: "#dcfce7",
    successSurfaceStrong: "#86efac",
    successStrong: "#22c55e",
    successText: "#166534",
    successBorder: "#bbf7d0",
    dangerSurface: "#fef2f2",
    dangerText: "#b91c1c",
    dangerStrong: "#ef4444",
    dangerBorder: "#fecaca",
    warningSurface: "#ffedd5",
    warningText: "#c2410c",
    warningBorder: "#fed7aa",
    warningStrong: "#f97316",
    warningSurfaceStrong: "#fde68a",
    violetSurface: "#ede9fe",
    violetText: "#6d28d9",
    neutralSurface: "#f1f5f9",
    neutralSurfaceStrong: "#f8fafc",
    neutralText: "#475569",
    neutralBorder: "#e5e7eb",
  },
  categories: {
    work: { background: "#dbeafe", text: "#1d4ed8", border: "#bfdbfe" },
    health: { background: "#fee2e2", text: "#b91c1c", border: "#fecaca" },
    learning: { background: "#f3e8ff", text: "#7e22ce", border: "#e9d5ff" },
    fitness: { background: "#dcfce7", text: "#15803d", border: "#bbf7d0" },
    creative: { background: "#fce7f3", text: "#be185d", border: "#fbcfe8" },
    personal: { background: "#ffedd5", text: "#c2410c", border: "#fed7aa" },
    custom: { background: "#fef3c7", text: "#a16207", border: "#fde68a" },
  },
} as const;

export const webCssVariables = {
  "--background": appPalette.surface.background,
  "--foreground": appPalette.surface.foreground,
  "--card": appPalette.surface.card,
  "--card-foreground": appPalette.surface.cardForeground,
  "--popover": appPalette.surface.popover,
  "--popover-foreground": appPalette.surface.popoverForeground,
  "--primary": appPalette.brand.primaryRgb,
  "--primary-foreground": appPalette.brand.primaryForeground,
  "--secondary": appPalette.ui.secondary,
  "--secondary-foreground": appPalette.ui.secondaryForeground,
  "--muted": appPalette.ui.muted,
  "--muted-foreground": appPalette.ui.mutedForeground,
  "--accent": appPalette.ui.accent,
  "--accent-foreground": appPalette.ui.accentForeground,
  "--destructive": appPalette.ui.destructive,
  "--destructive-foreground": appPalette.ui.destructiveForeground,
  "--border": appPalette.ui.border,
  "--input": appPalette.ui.input,
  "--input-background": appPalette.ui.inputBackground,
  "--switch-background": appPalette.ui.switchBackground,
  "--ring": appPalette.ui.ring,
  "--chart-1": appPalette.charts.chart1,
  "--chart-2": appPalette.charts.chart2,
  "--chart-3": appPalette.charts.chart3,
  "--chart-4": appPalette.charts.chart4,
  "--chart-5": appPalette.charts.chart5,
  "--sidebar": appPalette.sidebar.background,
  "--sidebar-foreground": appPalette.sidebar.foreground,
  "--sidebar-primary": appPalette.sidebar.primary,
  "--sidebar-primary-foreground": appPalette.sidebar.primaryForeground,
  "--sidebar-accent": appPalette.sidebar.accent,
  "--sidebar-accent-foreground": appPalette.sidebar.accentForeground,
  "--sidebar-border": appPalette.sidebar.border,
  "--sidebar-ring": appPalette.sidebar.ring,
} as const;
